<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE curso [
<!ELEMENT curso (nombre, descripcion?, (profesor | tutor)+, modulo*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT profesor (#PCDATA)>
<!ELEMENT tutor (#PCDATA)>
<!ELEMENT modulo (titulo, leccion+)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT leccion (#PCDATA)> ] >

<curso>
   <nombre>nombre</nombre>
   <descripcion>Descripcion</descripcion>
   <profesor>Profesor</profesor> 
   <tutor>Tutor</tutor> 
   <modulo>
     <titulo>Título</titulo>
     <leccion>Lección</leccion> 
   </modulo>
</curso>